# Spotify History Data Cleaning
## Loading into dataframe

In [2]:
import pandas as pd

fullHistory = pd.read_csv("./Spotify Extended Streaming History/full-history.csv")
fullHistory.sample(10)

C:\Users\User\AppData\Local\Temp\ipykernel_20548\1800744322.py:3: DtypeWarning: Columns (0: episode_name, 1: episode_show_name, 2: spotify_episode_uri) have mixed types. Specify dtype option on import or set low_memory=False.
  fullHistory = pd.read_csv("./Spotify Extended Streaming History/full-history.csv")

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
290288,2021-08-28T23:09:05Z,"iOS 14.7.1 (iPhone13,2)",255,GB,THE BENDS! - OG MIX,JPEGMAFIA,EP!,spotify:track:7yqmlcaGAE0Q6nZ9cNZ7NE,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,False,False,NaN,False
76864,2023-03-03T15:43:36Z,ios,90702,GB,Yum,slowthai,UGLY,spotify:track:6srSZ98GEz495b0ejEIVGl,NaN,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,True,True,False,1.677858e+09,False
122359,2024-03-30T06:20:22Z,ios,64885,GB,Neon Kitchen,Devon Hendryx,JOECHILLWORLD,spotify:track:7p4QiDvvgQLmvqKQUNFUsN,NaN,NaN,...,NaN,NaN,NaN,trackdone,unexpected-exit-while-paused,True,False,False,1.711780e+09,False
30514,2022-03-26T14:20:46Z,"iOS 15.3.1 (iPhone13,2)",230197,GB,The Place Where He Inserted the Blade,"Black Country, New Road",Ants From Up There,spotify:track:3k2kIiJqUiIP49iUcOLpWT,NaN,NaN,...,NaN,NaN,NaN,remote,trackdone,True,False,False,NaN,False
72465,2023-01-27T18:05:43Z,ios,86146,GB,1979 - Remastered 2012,The Smashing Pumpkins,Mellon Collie And The Infinite Sadness,spotify:track:5QLHGv0DfpeXLNFo7SFEy1,NaN,NaN,...,NaN,NaN,NaN,appload,unknown,True,False,False,1.674843e+09,False
309237,2021-11-25T08:08:18Z,"iOS 15.1 (iPhone13,2)",696,GB,Frontier Psychiatrist,The Avalanches,Since I Left You,spotify:track:4WVUtbd7CL38fVdIQVN3fk,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,backbtn,True,False,False,NaN,False
174470,2025-08-08T08:48:17Z,ios,322419,GB,Mental Health,Father John Misty,Mahashmashana,spotify:track:0VOCrdsydNicYcSTrjkk1f,NaN,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,True,True,False,1.754642e+09,False
194425,2025-09-28T20:12:20Z,ios,3871,GB,FLATLINE,Bladee,Cold Visions,spotify:track:2uUzWTAtMLbwu8YL1C53sN,NaN,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,True,True,False,1.759090e+09,False
292824,2021-09-06T22:04:58Z,"iOS 14.7.1 (iPhone13,2)",234475,GB,Things Behind The Sun,Nick Drake,Pink Moon,spotify:track:2s89qv9maW8RMCoaxtvNtn,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,NaN,False
236951,2021-01-02T19:27:38Z,"iOS 12.4.9 (iPhone7,2)",235866,GB,walking in the snow,Run The Jewels,RTJ4,spotify:track:2pVvB487ZwqdzTxEvEEors,NaN,NaN,...,NaN,NaN,NaN,playbtn,trackdone,True,False,False,NaN,False

In [3]:
# drop all podcast and audiobook rows
fullHistory = fullHistory[~fullHistory["episode_name"].notna()]
fullHistory = fullHistory[~fullHistory["audiobook_uri"].notna()]

# drop podcasts and audiobooks columns
fullHistory = fullHistory.drop(
    columns=[
        "episode_name",
        "episode_show_name",
        "spotify_episode_uri",
        "audiobook_title",
        "audiobook_chapter_uri",
        "audiobook_uri",
        "audiobook_chapter_title",
    ]
)

In [4]:
fullHistory.sample(10)

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
249397,2021-03-06T20:25:29Z,"iOS 14.4 (iPhone13,2)",211440,GB,Stay Away,Nirvana,Nevermind,spotify:track:0w7k0ZhHzkfEBsDmwp49xA,trackdone,trackdone,True,False,False,NaN,False
284443,2021-08-04T13:27:00Z,"iOS 14.6 (iPhone13,2)",251946,GB,when you sleep,my bloody valentine,loveless,spotify:track:2KylN9C0wNbzLgZNTG9oiU,trackdone,trackdone,False,False,False,NaN,False
134964,2024-06-25T21:28:50Z,ios,66510,GB,Spring breakers,Charli xcx,Brat and it’s the same but there’s three more ...,spotify:track:3dk7WaeS0y0JG0OMd0FVcg,trackdone,endplay,True,True,False,1.719351e+09,False
275340,2021-06-25T02:06:39Z,"iOS 14.6 (iPhone13,2)",316640,GB,The Moon,The Microphones,"The Glow, Pt. 2",spotify:track:4pbEwQiDjPln3oYlijXuOE,trackdone,trackdone,True,False,False,NaN,False
213025,2020-04-09T22:44:44Z,"iOS 12.4.5 (iPhone7,2)",6826,GB,Come As You Are,Nirvana,Nevermind,spotify:track:2RsAajgo0g7bMCHxwH3Sk0,clickrow,endplay,False,False,False,NaN,False
21421,2022-01-27T19:07:46Z,"iOS 15.2.1 (iPhone13,2)",859,GB,Candle,Sonic Youth,Daydream Nation (Remastered Original Album),spotify:track:7j8qXNeUNts3YxZ0hC1pi8,playbtn,endplay,True,False,False,NaN,False
241171,2021-01-25T13:03:37Z,"iOS 14.3 (iPhone13,2)",255386,GB,Nude,Radiohead,In Rainbows,spotify:track:35YyxFpE0ZTOoqFx5bADW8,playbtn,trackdone,False,False,False,NaN,False
239813,2021-01-19T21:42:47Z,"iOS 14.3 (iPhone13,2)",2275,GB,In the Aeroplane Over the Sea,Neutral Milk Hotel,In the Aeroplane Over the Sea,spotify:track:4OciRObYGzPzlU40U7YRc8,playbtn,endplay,False,False,False,NaN,False
204951,2020-01-18T18:30:13Z,"iOS 12.4.4 (iPhone6,2)",3227,GB,¿Viva La Gloria? (Little Girl),Green Day,21st Century Breakdown,spotify:track:2mnk1GHN0XmznKiucY4ZW4,clickrow,fwdbtn,False,False,True,1.579371e+12,False
87336,2023-05-28T12:30:19Z,ios,2281,GB,Operator,Yves Tumor,Praise A Lord Who Chews But Which Does Not Con...,spotify:track:6wsmCMlFGX4jOko2I3bUtb,trackdone,fwdbtn,True,True,False,1.685277e+09,False

In [5]:
# drop irrelevant columns
fullHistory = fullHistory.drop(
    columns=[
        "platform",
        "spotify_track_uri",
        "shuffle",
        "offline",
        "offline_timestamp",
        "incognito_mode"
    ]
)

In [24]:
fullHistory.to_csv("./Spotify Extended Streaming History/cleaned-history.csv", index=False)