# Spotify History Data Cleaning
## Loading into dataframe

In [2]:
import pandas as pd

fullHistory = pd.read_csv("./Spotify Extended Streaming History/full-history.csv")
fullHistory.sample(10)

C:\Users\User\AppData\Local\Temp\ipykernel_20372\1800744322.py:3: DtypeWarning: Columns (0: episode_name, 1: episode_show_name, 2: spotify_episode_uri) have mixed types. Specify dtype option on import or set low_memory=False.
  fullHistory = pd.read_csv("./Spotify Extended Streaming History/full-history.csv")

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
282011,2021-07-23T15:00:31Z,"iOS 14.6 (iPhone13,2)",882,GB,See You Again (feat. Kali Uchis),"Tyler, The Creator",Flower Boy,spotify:track:7KA4W4McWYRpgf0fWsJZWB,NaN,NaN,...,NaN,NaN,NaN,playbtn,endplay,True,False,False,NaN,False
65714,2022-12-05T19:57:58Z,ios,11424,GB,Kids,PUP,Morbid Stuff,spotify:track:6Dgix2xCbnqigfrjulm24R,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,endplay,True,True,False,1.670270e+09,False
136829,2024-07-09T13:19:03Z,ios,362293,GB,My Jamaican Guy,Grace Jones,Living My Life,spotify:track:7zcC5yZZp1IKnI73ztsIaE,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,True,False,False,1.720531e+09,False
215077,2020-05-04T11:05:01Z,"iOS 12.4.5 (iPhone7,2)",193000,GB,Brain Stew,Green Day,Insomniac,spotify:track:1nLnpLXvl68RZCSjfkyiaa,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
289786,2021-08-27T09:40:51Z,"iOS 14.7.1 (iPhone13,2)",154799,GB,Itch,Ewy,World Is Mine,spotify:track:2pipmcMfejCPuOAwPoiFQQ,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,NaN,False
143675,2024-09-04T16:07:23Z,ios,1184,GB,Two Worlds Apart,Little Simz,Sometimes I Might Be Introvert,spotify:track:34qvgmIagzNQdZTRL2poiv,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,True,True,False,1.725466e+09,False
42555,2022-06-20T16:47:35Z,"iOS 15.5 (iPhone13,2)",3482,GB,Bruja,Arca,KicK iii,spotify:track:4DbRtnuP6eyQSGXbquLRv0,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,False,True,1.655744e+12,False
76071,2023-02-24T08:39:02Z,ios,11958,GB,Ceremony,Skrillex,Don’t Get Too Close,spotify:track:4DmqWDZUtoxBX7wg9eCgzF,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,1.677228e+09,False
280776,2021-07-16T16:54:47Z,"iOS 14.6 (iPhone13,2)",617746,GB,Viðrar vel til loftárása,Sigur Rós,Ágætis byrjun,spotify:track:1blbT2vGiqxICPoyxzfVn1,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,NaN,False
58308,2022-10-03T20:20:25Z,"iOS 15.6.1 (iPhone13,2)",132773,GB,Brand New City,Mitski,Lush,spotify:track:47k7FCxk7ylTwKCnJ3QTVc,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,True,False,False,NaN,False

In [ ]:
# drop all podcast and audiobook rows
fullHistory = fullHistory[~fullHistory["episode_name"].notna()]
fullHistory = fullHistory[~fullHistory["audiobook_uri"].notna()]

# drop podcasts and audiobooks columns
fullHistory = fullHistory.drop(
    columns=[
        "episode_name",
        "episode_show_name",
        "spotify_episode_uri",
        "audiobook_title",
        "audiobook_chapter_uri",
        "audiobook_uri",
        "audiobook_chapter_title",
    ]
)

In [18]:
fullHistory.sample(10)

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
10428,2019-04-12T17:31:15Z,"iOS 12.2 (iPhone6,2)",696,GB,Young Volcanoes,Fall Out Boy,Save Rock And Roll,spotify:track:4yXNMbZrsFJbPTH0WfhwEB,clickrow,endplay,True,False,False,NaN,False
15988,2021-12-23T19:36:21Z,"iOS 15.1.1 (iPhone13,2)",1950,GB,All I Need,Radiohead,In Rainbows,spotify:track:5Qv2Nby1xTr9pQyjkrc94J,playbtn,endplay,True,False,False,NaN,False
312995,2021-12-19T15:18:55Z,"iOS 15.1.1 (iPhone13,2)",534,GB,Heaven and Hell,Kanye West,Donda,spotify:track:2Y40huo5ewaKYxsFintYtF,fwdbtn,fwdbtn,False,False,False,NaN,False
107359,2023-11-22T00:08:16Z,ios,1787,GB,I Don't Love Me Anymore,Oneohtrix Point Never,Magic Oneohtrix Point Never,spotify:track:1VyvcAAHK9sbKi1ZC34IBb,clickrow,endplay,True,True,False,1.700612e+09,False
232698,2020-11-17T23:52:03Z,"iOS 12.4.8 (iPhone7,2)",253586,GB,505,Arctic Monkeys,Favourite Worst Nightmare,spotify:track:0BxE4FqsDD1Ot4YuBXwAPp,trackdone,trackdone,True,False,False,NaN,False
149107,2024-10-30T18:33:45Z,ios,146225,GB,crush,2hollis,crush,spotify:track:7oUMu1A4dgci1erq7TfeBi,fwdbtn,trackdone,True,False,False,1.730313e+09,False
201680,2026-01-18T15:12:35Z,ios,2113,CH,Fire Dance,Dizzy Gillespie,Free Ride,spotify:track:3lhNPeZgnuUigHq11zA0uS,fwdbtn,fwdbtn,True,True,False,1.768749e+09,False
895,2017-05-31T08:17:57Z,"iOS 9.3.5 (iPad2,1)",3459,GB,Rich Boy,Galantis,Rich Boy,spotify:track:0K7Dd9DP6fvOl0mrlX0aUa,fwdbtn,fwdbtn,True,False,False,NaN,False
277097,2021-07-02T17:19:50Z,"iOS 14.6 (iPhone13,2)",8223,GB,45 SMOKE,slowthai,TYRON,spotify:track:52dZyvQ3mSuS76t9Dok4hq,trackdone,endplay,True,False,False,NaN,False
179493,2019-06-21T14:47:36Z,"iOS 12.3.1 (iPhone6,2)",197573,GB,Talk (feat. Disclosure),Khalid,Free Spirit,spotify:track:6TqXcAFInzjp0bODyvrWEq,trackdone,trackdone,True,False,True,1.561117e+12,False

In [ ]:
# drop irrelevant columns
fullHistory = fullHistory.drop(
    columns=[
        "platform",
        "spotify_track_uri",
        "shuffle",
        "offline",
        "offline_timestamp",
        "incognito_mode"
    ]
)

In [22]:
fullHistory[fullHistory['master_metadata_track_name'] == "Lover, You Should've Come Over"]

,ts,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,reason_start,reason_end,skipped
65485,2022-12-04T01:06:48Z,404213,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,fwdbtn,trackdone,False
65486,2022-12-04T01:14:30Z,404213,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,trackdone,trackdone,False
65492,2022-12-04T11:05:45Z,404213,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,fwdbtn,trackdone,False
65495,2022-12-04T11:18:05Z,404213,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,clickrow,trackdone,False
65496,2022-12-04T11:26:30Z,404213,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,trackdone,trackdone,False
...,...,...,...,...,...,...,...,...,...
125539,2024-04-20T16:34:50Z,2229,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,clickrow,endplay,True
133601,2024-06-13T15:57:58Z,207,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,trackdone,fwdbtn,True
149181,2024-10-31T15:19:51Z,1393,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,fwdbtn,fwdbtn,True
149210,2024-10-31T17:37:30Z,248446,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,trackdone,fwdbtn,True
154079,2024-12-20T13:35:11Z,6757,GB,"Lover, You Should've Come Over",Jeff Buckley,Grace,playbtn,endplay,True