# Spotify History Data Cleaning
## Loading into dataframe

In [ ]:
import pandas as pd

fullHistory = pd.read_csv("./Spotify Extended Streaming History/raw/full-history.csv")
fullHistory.sample(10)

C:\Users\User\AppData\Local\Temp\ipykernel_23452\1800744322.py:3: DtypeWarning: Columns (0: episode_name, 1: episode_show_name, 2: spotify_episode_uri) have mixed types. Specify dtype option on import or set low_memory=False.
  fullHistory = pd.read_csv("./Spotify Extended Streaming History/full-history.csv")

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
2095,2018-05-28T12:02:03Z,"iOS 11.3.1 (iPhone6,2)",363521,GB,Rap God,Eminem,The Marshall Mathers LP2,spotify:track:6sDQ4uiWw9OdVrCXFLSlZt,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,True,False,False,NaN,False
75558,2023-02-19T12:07:17Z,ios,190613,GB,Hollywood Forever Cemetery Sings,Father John Misty,Fear Fun,spotify:track:3O30ywyRk6EKT68sBvVqOP,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,1.676808e+09,False
53522,2022-08-23T12:10:46Z,"iOS 15.6 (iPhone13,2)",123452,GB,CHALICE OF MIND,Yabujin,CHALICE OF MIND,spotify:track:4GTaNTujKpfoFDcCTZEfc4,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,NaN,False
155294,2025-01-06T20:39:31Z,ios,369600,GB,Like a Rolling Stone,Bob Dylan,Highway 61 Revisited,spotify:track:3AhXZa8sUQht0UEdBJgpGc,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,True,False,True,1.736196e+09,False
167164,2025-05-14T14:55:16Z,ios,1555,GB,Dry Hands,C418,Minecraft - Volume Alpha,spotify:track:1gNcPHAiVIQZmqJFJdt3ti,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,1.747235e+09,False
218048,2020-06-11T11:55:52Z,"iOS 12.4.6 (iPhone7,2)",1230,GB,One Of My Turns - 2011 Remastered Version,Pink Floyd,The Wall (Remastered),spotify:track:0MW7g3oFkdmZIiomSGC4x4,NaN,NaN,...,NaN,NaN,NaN,playbtn,endplay,True,False,False,NaN,False
144581,2024-09-15T19:28:12Z,ios,146285,GB,Talk talk featuring troye sivan,Charli xcx,Talk talk featuring troye sivan,spotify:track:2LUD3874dlzeRa34Hi7ohW,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,True,True,False,1.726426e+09,False
80269,2023-03-27T09:47:59Z,ios,252671,GB,Eye Know,De La Soul,3 Feet High and Rising,spotify:track:4xQMFoD33vx6stB1UzfA6s,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,True,1.679910e+09,False
48012,2022-07-18T20:27:28Z,"iOS 15.5 (iPhone13,2)",118933,GB,I'm So Tired,Fugazi,Instrument Soundtrack,spotify:track:6JgHKt0WwdwlXIht6M0mqa,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,True,False,False,NaN,False
210646,2020-03-25T12:46:10Z,"iOS 12.4.5 (iPhone7,2)",14860,GB,I'm Happy Just To Dance With You - Remastered ...,The Beatles,A Hard Day's Night,spotify:track:0gd50I2gKioJ59C827EdAY,NaN,NaN,...,NaN,NaN,NaN,clickrow,endplay,False,False,False,NaN,False

In [2]:
# drop all podcast and audiobook rows
fullHistory = fullHistory[~fullHistory["episode_name"].notna()]
fullHistory = fullHistory[~fullHistory["audiobook_uri"].notna()]

# drop podcasts and audiobooks columns
fullHistory = fullHistory.drop(
    columns=[
        "episode_name",
        "episode_show_name",
        "spotify_episode_uri",
        "audiobook_title",
        "audiobook_chapter_uri",
        "audiobook_uri",
        "audiobook_chapter_title",
    ]
)

In [3]:
fullHistory.sample(10)

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
32068,2022-04-09T11:51:25Z,"iOS 15.3.1 (iPhone13,2)",143004,PT,Disappointing Diamonds Are the Rarest of Them All,Father John Misty,God's Favorite Customer,spotify:track:2FkD2soiPgO7MGo4wjTk12,trackdone,trackdone,True,False,True,1.649496e+12,False
52785,2022-08-18T00:10:33Z,"iOS 15.6 (iPhone13,2)",248960,GB,Mystery of Love,Sufjan Stevens,Mystery of Love,spotify:track:5GbVzc6Ex5LYlLJqzRQhuy,trackdone,trackdone,True,False,False,NaN,False
72942,2023-01-31T17:24:40Z,ios,23754,GB,Watch,Arca,KiCk i,spotify:track:6BTaOTV4R07QunBda62fR7,fwdbtn,fwdbtn,True,True,False,1.675186e+09,False
8235,2019-03-09T12:48:03Z,"iOS 12.1.4 (iPhone6,2)",789,GB,Momentz (feat. De La Soul),Gorillaz,Humanz,spotify:track:2RCp9QBnFSxdKe8RD4xF8s,clickrow,endplay,True,False,False,NaN,False
94641,2023-08-01T09:08:25Z,ios,117809,GB,Speed Drive,Charli xcx,Barbie The Album,spotify:track:7GRv55NwkjxU2ysJLwzC9c,trackdone,trackdone,True,False,False,1.690881e+09,False
18825,2022-01-12T19:42:43Z,"iOS 15.1.1 (iPhone13,2)",432680,GB,Changes,Charles Bradley,Changes,spotify:track:1fOc4Kf82a6J1C9gS5sE0d,fwdbtn,fwdbtn,True,False,False,NaN,False
122639,2024-03-31T14:42:39Z,ios,69892,GB,"Any Time, Any Place",Janet Jackson,Janet,spotify:track:2yOm4lN7aTygtXanJFNFWU,fwdbtn,fwdbtn,True,True,False,1.711896e+09,False
158491,2025-02-07T12:22:41Z,ios,5619,GB,Time: The Donut of the Heart,J Dilla,Donuts,spotify:track:6ywnTBL62OTd8HUaztJizb,fwdbtn,fwdbtn,True,True,False,1.738931e+09,False
11778,2019-04-21T12:55:19Z,"iOS 12.2 (iPhone6,2)",2739,GB,Know Me,Marshmello,Joytime,spotify:track:1aS1uzcAC14lduwuNJZjqE,clickrow,endplay,True,False,False,NaN,False
65817,2022-12-06T21:53:16Z,ios,8521,GB,Something In The Way,Nirvana,Nevermind,spotify:track:4gHnSNHs8RyVukKoWdS99f,backbtn,endplay,True,True,False,1.670364e+09,False

In [4]:
# drop irrelevant columns
fullHistory = fullHistory.drop(
    columns=[
        "platform",
        "spotify_track_uri",
        "shuffle",
        "offline",
        "offline_timestamp",
        "incognito_mode"
    ]
)

In [38]:
fullHistory['ts'] = pd.to_datetime(fullHistory['ts'])

In [ ]:
fullHistory.to_csv("./Spotify Extended Streaming History/cleaned/cleaned-history.csv", index=False)

In [7]:
# top artist by play count
topArtists = fullHistory["master_metadata_album_artist_name"].value_counts().head(10)
print("Top 10 Artists by Play Count:")
print(topArtists)

Top 10 Artists by Play Count:
master_metadata_album_artist_name
Gorillaz                            8471
The Beatles                         6727
Radiohead                           5370
Kanye West                          4948
Elliott Smith                       4778
Green Day                           4449
Death Grips                         4210
Bladee                              3989
King Gizzard & The Lizard Wizard    3943
Kendrick Lamar                      3683
Name: count, dtype: int64

## Function to Split History by Year

In [19]:
def historySplit(df, year):
    return df[df['ts'].dt.year == year]

In [32]:
history2023 = historySplit(fullHistory, 2023)

In [37]:
history2023.sample(10)

,ts,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,reason_start,reason_end,skipped
81168,2023-04-04 19:55:49+00:00,780,GB,Helpless Child,Swans,Soundtracks for the Blind,remote,fwdbtn,True
102016,2023-10-01 22:44:00+00:00,207707,GB,Make Believe,Kero Kero Bonito,Time 'n' Place,trackdone,trackdone,False
70984,2023-01-13 22:43:55+00:00,166003,GB,mememe,100 gecs,mememe,fwdbtn,trackdone,False
83379,2023-04-25 22:36:19+00:00,14442,GB,All My Friends,LCD Soundsystem,Sound of Silver,fwdbtn,fwdbtn,True
98694,2023-09-04 07:56:57+00:00,59520,GB,Iron Lung,King Gizzard & The Lizard Wizard,"Ice, Death, Planets, Lungs, Mushrooms And Lava",trackdone,fwdbtn,True
70685,2023-01-11 21:47:20+00:00,165250,GB,COCONUT PERFUME,Ray Laurél,MANIC PIXIE DREAM BOY,trackdone,trackdone,False
102943,2023-10-10 15:24:22+00:00,6965,GB,Zero - Remastered 2012,The Smashing Pumpkins,Mellon Collie And The Infinite Sadness,fwdbtn,endplay,True
88950,2023-06-09 19:41:47+00:00,29601,GB,Loving Machine,TV Girl,Who Really Cares,trackdone,endplay,True
106712,2023-11-15 22:58:05+00:00,3668,GB,"Holy Fucking Shit: 40,000",Have A Nice Life,Deathconsciousness,playbtn,fwdbtn,True
72429,2023-01-26 22:52:24+00:00,214490,GB,Walking the Cow,Daniel Johnston,Hi How Are You,trackdone,trackdone,False